[package]
name = "hw6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"

[lib]
name = "my_lib"
path = "src/lib/mod.rs"

[[bin]]
name = "todo_name"
path = "src/bin/main.rs"
